services:
  prospecta-front-prod:
    image: ${FULL_IMAGE_NAME}
    container_name: prospecta-front-prod
    restart: always

    ports:
      - "127.0.0.1:3000:80"

    networks:
      - infrastructure-network

    environment:
      - NODE_ENV=production

    # env_file:
    #   - prospecta-front-prod.env

networks:
  infrastructure-network:
    external: true