version: '3.8'

services:
  prospecta-front-prod:
    image: ${FULL_IMAGE_NAME:-ghcr.io/ndoucoumane/prospecta-front:latest}
    container_name: prospecta-front-prod
    restart: always
    ports:
      - "3000:80"
    networks:
      - infrastructure-network
    environment:
      - NODE_ENV=production
    # env_file:
    #   - prospecta-front-prod.env

networks:
  infrastructure-network:
    external: true
