import type {
  User,
  Organization,
  Prospect,
  Company,
  Campaign,
  Conversation,
  Message,
  Opportunity,
  AnalyticsSummary,
} from '../types';

export const initialUser: User = {
  id: 'usr-mor-01',
  email: 'mor@prospecta.sn',
  firstName: 'Mor',
  lastName: 'Keblink',
  role: 'Directeur Commercial',
  organizationId: 'org-sn-01',
  organizationName: 'Prospecta Sénégal',
  avatarUrl: '',
};

export const initialOrganization: Organization = {
  id: 'org-sn-01',
  name: 'Prospecta Sénégal',
  currency: 'FCFA',
  timezone: 'Africa/Dakar',
  country: 'Sénégal',
  phonePrefix: '+221',
  whatsappConnected: true,
  whatsappPhoneNumber: '+221 77 845 12 34',
  whatsappAccountName: 'Prospecta Commercial Business',
};

export const initialCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'Teranga Logistique & Transit',
    sector: 'Transport & Logistique',
    city: 'Dakar',
    website: 'https://terangalogistique.sn',
    size: '51-200',
    contactCount: 3,
    score: 92,
    phone: '+221 33 821 44 00',
    createdAt: '2026-02-10T09:00:00Z',
    aiAnalysis: {
      summary: 'Acteur majeur de la logistique portuaire à Dakar en pleine phase d\'expansion vers la sous-région ouest-africaine. Modernisation active des outils de suivi client et recherche de partenaires fiables.',
      keyPoints: [
        'Croissance de +28% de la flotte de camions en 2025',
        'Volonté affichée de digitaliser la relation transporteur-chargeur',
        'Direction commerciale très réactive sur WhatsApp'
      ],
      opportunities: [
        'Automatisation des relances de devis de fret',
        'Intégration d\'un canal de notification client WhatsApp',
        'Offre B2B sur-mesure pour les transitaires partenaires'
      ],
      recommendedApproach: 'Contacter en priorité Babacar Ndiaye (Directeur Général) par WhatsApp avec une proposition orientée réduction des délais de qualification et suivi automatique des expéditions.',
      lastAnalyzedAt: '2026-03-01T14:30:00Z',
    },
  },
  {
    id: 'comp-2',
    name: 'Hôtel Terrou-Bi Dakar',
    sector: 'Hôtellerie & Restauration',
    city: 'Dakar',
    website: 'https://terroubi.com',
    size: '200+',
    contactCount: 4,
    score: 87,
    phone: '+221 33 839 90 00',
    createdAt: '2026-01-15T11:20:00Z',
    aiAnalysis: {
      summary: 'Établissement 5 étoiles de référence sur la Corniche Ouest de Dakar. Forte activité corporate, séminaires internationaux et événementiel d\'affaires.',
      keyPoints: [
        'Budget commercial et marketing en hausse pour les séminaires',
        'Clientèle B2B internationale et régionale exigeante',
        'Cycle d\'achat concentré sur les Q1 et Q3'
      ],
      opportunities: [
        'Campagne multicanale pour les réservations de salles de conférences B2B',
        'Relance personnalisée des entreprises pour banquets et événements de fin d\'année'
      ],
      recommendedApproach: 'S\'adresser à la Direction Commerciale avec une étude de cas prouvant le remplissage des événements corporate via prospection ciblée.',
      lastAnalyzedAt: '2026-02-20T10:00:00Z',
    },
  },
  {
    id: 'comp-3',
    name: 'SenAgro Industries',
    sector: 'Agroalimentaire',
    city: 'Thiès',
    website: 'https://senagro.sn',
    size: '51-200',
    contactCount: 2,
    score: 79,
    phone: '+221 33 951 12 10',
    createdAt: '2026-02-05T08:00:00Z',
    aiAnalysis: {
      summary: 'Pôle de transformation agro-industrielle basé dans la zone industrielle de Thiès, distribuant dans tout le Sénégal et exportant vers la Gambie et le Mali.',
      keyPoints: [
        'Réseau de grossistes et semi-grossistes dense à animer',
        'Sensible aux solutions améliorant le taux de conversion commerciale',
        'Processus de décision collégial (Directeur Général + Dir. Commercial)'
      ],
      opportunities: [
        'Campagnes de réactivation des distributeurs inactifs',
        'Séquences de qualification directe par SMS & WhatsApp pour le réseau commercial'
      ],
      recommendedApproach: 'Mettre en avant l\'automatisation des commandes répétitives et la qualification rapide des nouveaux distributeurs régionaux.',
      lastAnalyzedAt: '2026-02-18T16:00:00Z',
    },
  },
  {
    id: 'comp-4',
    name: 'Baobab Distribution',
    sector: 'Commerce & Distribution',
    city: 'Saly',
    website: 'https://baobabdistrib.sn',
    size: '11-50',
    contactCount: 2,
    score: 68,
    phone: '+221 33 957 88 90',
    createdAt: '2026-02-22T13:45:00Z',
  },
  {
    id: 'comp-5',
    name: 'Dakar Tech Solutions',
    sector: 'Technologies & Logiciels',
    city: 'Dakar',
    website: 'https://dakartech.sn',
    size: '11-50',
    contactCount: 2,
    score: 84,
    phone: '+221 33 864 55 22',
    createdAt: '2026-01-28T15:10:00Z',
  }
];

export const initialProspects: Prospect[] = [
  {
    id: 'pros-1',
    firstName: 'Babacar',
    lastName: 'Ndiaye',
    email: 'b.ndiaye@terangalogistique.sn',
    phone: '+221 77 645 32 10',
    companyId: 'comp-1',
    companyName: 'Teranga Logistique & Transit',
    jobTitle: 'Directeur Général',
    city: 'Dakar',
    sector: 'Transport & Logistique',
    score: {
      score: 92,
      level: 'Élevé',
      factors: [
        { label: 'Correspondance ICP', points: 30, description: 'Secteur prioritaire et taille cible' },
        { label: 'Décideur identifié', points: 25, description: 'Directeur Général avec pouvoir d\'achat direct' },
        { label: 'Secteur cible', points: 20, description: 'Transport & Logistique en forte demande' },
        { label: 'Présence digitale & réactivité', points: 17, description: 'Numéro WhatsApp actif vérifié' },
      ],
    },
    status: 'qualified',
    source: 'campaign',
    lastActivityAt: '2026-03-05T10:15:00Z',
    createdAt: '2026-02-12T09:00:00Z',
    notes: 'Très intéressé par une démonstration orientée suivi client et relances WhatsApp.',
  },
  {
    id: 'pros-2',
    firstName: 'Aïssatou',
    lastName: 'Diop',
    email: 'aissatou.diop@terroubi.com',
    phone: '+221 78 123 45 67',
    companyId: 'comp-2',
    companyName: 'Hôtel Terrou-Bi Dakar',
    jobTitle: 'Directrice Commerciale',
    city: 'Dakar',
    sector: 'Hôtellerie & Restauration',
    score: {
      score: 87,
      level: 'Élevé',
      factors: [
        { label: 'Correspondance ICP', points: 25, description: 'Hôtellerie d\'affaires haut de gamme' },
        { label: 'Secteur cible', points: 20, description: 'Secteur porteur pour les campagnes B2B' },
        { label: 'Décideur identifié', points: 20, description: 'Directrice Commerciale' },
        { label: 'Présence digitale', points: 12, description: 'Profil professionnel actif et coordonnées vérifiées' },
        { label: 'Engagement récent', points: 10, description: 'A répondu à notre email de prospection' },
      ],
    },
    status: 'meeting',
    source: 'campaign',
    lastActivityAt: '2026-03-06T14:20:00Z',
    createdAt: '2026-02-15T10:30:00Z',
    notes: 'Rendez-vous de démonstration prévu pour jeudi à 11h.',
  },
  {
    id: 'pros-3',
    firstName: 'Cheikh',
    lastName: 'Fall',
    email: 'c.fall@senagro.sn',
    phone: '+221 76 555 89 01',
    companyId: 'comp-3',
    companyName: 'SenAgro Industries',
    jobTitle: 'Directeur Commercial & Distribution',
    city: 'Thiès',
    sector: 'Agroalimentaire',
    score: {
      score: 79,
      level: 'Moyen',
      factors: [
        { label: 'Correspondance ICP', points: 25, description: 'PME manufacturière régionale' },
        { label: 'Décideur identifié', points: 20, description: 'Directeur Commercial' },
        { label: 'Secteur cible', points: 20, description: 'Industrie et distribution' },
        { label: 'Présence digitale', points: 14, description: 'Présence LinkedIn confirmée' },
      ],
    },
    status: 'contacted',
    source: 'manual',
    lastActivityAt: '2026-03-04T16:45:00Z',
    createdAt: '2026-02-18T14:00:00Z',
    notes: 'Premier message envoyé par WhatsApp. En attente de lecture.',
  },
  {
    id: 'pros-4',
    firstName: 'Ousmane',
    lastName: 'Sow',
    email: 'o.sow@baobabdistrib.sn',
    phone: '+221 77 341 90 82',
    companyId: 'comp-4',
    companyName: 'Baobab Distribution',
    jobTitle: 'Responsable des Achats',
    city: 'Saly',
    sector: 'Commerce & Distribution',
    score: {
      score: 68,
      level: 'Moyen',
      factors: [
        { label: 'Correspondance ICP', points: 20, description: 'Structure moyenne en province' },
        { label: 'Secteur cible', points: 18, description: 'Distribution régionale' },
        { label: 'Décideur identifié', points: 15, description: 'Responsable achats' },
        { label: 'Présence digitale', points: 15, description: 'Email professionnel actif' },
      ],
    },
    status: 'new',
    source: 'csv',
    lastActivityAt: '2026-03-01T08:30:00Z',
    createdAt: '2026-03-01T08:30:00Z',
  },
  {
    id: 'pros-5',
    firstName: 'Mariama',
    lastName: 'Ba',
    email: 'mariama@dakartech.sn',
    phone: '+221 77 912 34 56',
    companyId: 'comp-5',
    companyName: 'Dakar Tech Solutions',
    jobTitle: 'Chief Growth Officer',
    city: 'Dakar',
    sector: 'Technologies & Logiciels',
    score: {
      score: 84,
      level: 'Élevé',
      factors: [
        { label: 'Correspondance ICP', points: 25, description: 'Entreprise de services tech en forte croissance' },
        { label: 'Décideur identifié', points: 25, description: 'En charge du développement commercial' },
        { label: 'Secteur cible', points: 20, description: 'SaaS et solutions numériques' },
        { label: 'Présence digitale', points: 14, description: 'Présence multi-canal forte' },
      ],
    },
    status: 'qualified',
    source: 'linkedin',
    lastActivityAt: '2026-03-06T11:00:00Z',
    createdAt: '2026-02-25T11:00:00Z',
  },
];

export const initialCampaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Hôtels Dakar — Événementiel B2B',
    objective: 'Obtenir des rendez-vous de démonstration avec les directeurs commerciaux',
    icp: 'Hôtels 3 à 5 étoiles et complexes hôteliers de Dakar',
    status: 'active',
    channels: ['email', 'whatsapp'],
    totalProspects: 48,
    sentCount: 48,
    replyCount: 16,
    meetingCount: 7,
    targetAudience: 'Directeurs Commerciaux, Directeurs Généraux',
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-03-06T12:00:00Z',
    steps: [
      {
        stepNumber: 1,
        channel: 'email',
        delayDays: 0,
        subject: 'Optimisation de vos réservations d\'affaires — {{companyName}}',
        content: 'Bonjour {{firstName}},\n\nJ\'ai remarqué le dynamisme de {{companyName}} sur le marché hôtelier à {{city}}.\n\nNous aidons les directeurs commerciaux à centraliser leurs prospects d\'affaires et à multiplier par deux le taux de réponse de leurs campagnes d\'entreprises partenaires.\n\nSeriez-vous ouvert à un échange de 15 minutes ce jeudi pour voir comment cela s\'applique à {{companyName}} ?\n\nBien à vous,\nMor Keblink',
      },
      {
        stepNumber: 2,
        channel: 'whatsapp',
        delayDays: 2,
        content: 'Bonjour {{firstName}}, c\'est Mor de Prospecta. Je fais suite à mon email concernant la prospection commerciale de {{companyName}}. Avez-vous eu l\'occasion de le consulter ? Bien cordialement.',
      },
      {
        stepNumber: 3,
        channel: 'email',
        delayDays: 4,
        subject: 'Retour suite à notre échange — {{firstName}}',
        content: 'Bonjour {{firstName}},\n\nJe me permets une brève relance pour savoir si le développement de votre portefeuille clients corporate à {{city}} est un sujet d\'actualité ce trimestre pour {{companyName}}.\n\nRestant à votre disposition,\nMor Keblink',
      },
    ],
  },
  {
    id: 'camp-2',
    name: 'Logistique & Transit Portuaire Dakar',
    objective: 'Qualifier les entreprises de transit maritime et logistique',
    icp: 'Entreprises de logistique et transit de Dakar de plus de 20 employés',
    status: 'active',
    channels: ['whatsapp', 'email'],
    totalProspects: 34,
    sentCount: 34,
    replyCount: 11,
    meetingCount: 5,
    targetAudience: 'Directeurs Généraux, Responsables Logistique',
    createdAt: '2026-02-20T11:00:00Z',
    updatedAt: '2026-03-05T15:00:00Z',
    steps: [
      {
        stepNumber: 1,
        channel: 'whatsapp',
        delayDays: 0,
        content: 'Bonjour M. {{lastName}}, je suis Mor Keblink de Prospecta. Nous accompagnons les leaders du transit à Dakar dans la qualification automatique de leurs prospects import-export. Seriez-vous disponible pour un court appel demain ?',
      },
      {
        stepNumber: 2,
        channel: 'email',
        delayDays: 3,
        subject: 'Accélération commerciale chez {{companyName}}',
        content: 'Bonjour {{firstName}},\n\nPour faire suite à mon message, voici une courte présentation des opportunités que nous identifions pour {{companyName}} dans le secteur logistique.\n\nExcellente journée,\nMor Keblink',
      },
    ],
  },
  {
    id: 'camp-3',
    name: 'Agro-alimentaire & Distribution Régionale',
    objective: 'Prise de contact avec les grossistes et industriels',
    icp: 'Industries de transformation et distributeurs agro à Dakar et Thiès',
    status: 'draft',
    channels: ['email'],
    totalProspects: 26,
    sentCount: 0,
    replyCount: 0,
    meetingCount: 0,
    targetAudience: 'Directeurs Commerciaux',
    createdAt: '2026-03-02T09:30:00Z',
    updatedAt: '2026-03-02T09:30:00Z',
    steps: [
      {
        stepNumber: 1,
        channel: 'email',
        delayDays: 0,
        subject: 'Développement de votre réseau de distribution — {{companyName}}',
        content: 'Bonjour {{firstName}},\n\nComment gérez-vous actuellement l\'activation de nouveaux distributeurs régionaux pour {{companyName}} ?\n\nProspecta vous permet d\'identifier et relancer automatiquement les revendeurs cibles.\n\nBien cordialement,\nMor Keblink',
      },
    ],
  },
];

export const initialConversations: Conversation[] = [
  {
    id: 'conv-1',
    prospectId: 'pros-2',
    prospectName: 'Aïssatou Diop',
    companyName: 'Hôtel Terrou-Bi Dakar',
    channel: 'email',
    lastMessage: 'Bonjour Mor, la démonstration m\'intéresse. Êtes-vous disponible ce jeudi à 11h ?',
    lastMessageAt: '2026-03-06T14:20:00Z',
    unread: false,
    suggestedReply: 'Bonjour Aïssatou, merci pour votre retour. C\'est parfait pour ce jeudi à 11h. Je vous transmets le lien d\'invitation immédiatement.',
  },
  {
    id: 'conv-2',
    prospectId: 'pros-1',
    prospectName: 'Babacar Ndiaye',
    companyName: 'Teranga Logistique & Transit',
    channel: 'whatsapp',
    lastMessage: 'Bonjour, pouvez-vous me préciser les tarifs pour une équipe de 5 commerciaux ?',
    lastMessageAt: '2026-03-05T10:15:00Z',
    unread: true,
    suggestedReply: 'Bonjour M. Ndiaye, pour 5 commerciaux, notre offre Business est à 150 000 FCFA/mois tout inclus (WhatsApp multicanal illimité et IA). Je peux vous envoyer le devis détaillé.',
  },
  {
    id: 'conv-3',
    prospectId: 'pros-5',
    prospectName: 'Mariama Ba',
    companyName: 'Dakar Tech Solutions',
    channel: 'email',
    lastMessage: 'Bonjour Mor, nous sommes en train de revoir nos outils de prospection pour Q2. Discutons-en la semaine prochaine.',
    lastMessageAt: '2026-03-06T11:00:00Z',
    unread: false,
    suggestedReply: 'Bonjour Mariama, avec grand plaisir. Quel jour vous conviendrait le mieux entre mardi et mercredi prochain ?',
  },
];

export const initialMessages: Record<string, Message[]> = {
  'conv-1': [
    {
      id: 'msg-101',
      conversationId: 'conv-1',
      sender: 'user',
      content: 'Bonjour Aïssatou,\n\nJ\'ai remarqué le dynamisme de l\'Hôtel Terrou-Bi Dakar sur le marché hôtelier à Dakar.\n\nNous aidons les directeurs commerciaux à centraliser leurs prospects d\'affaires et à multiplier par deux le taux de réponse de leurs campagnes d\'entreprises partenaires.\n\nSeriez-vous ouverte à un échange de 15 minutes ce jeudi ?',
      channel: 'email',
      timestamp: '2026-03-05T09:30:00Z',
      status: 'read',
    },
    {
      id: 'msg-102',
      conversationId: 'conv-1',
      sender: 'prospect',
      content: 'Bonjour Mor, la démonstration m\'intéresse. Êtes-vous disponible ce jeudi à 11h ?',
      channel: 'email',
      timestamp: '2026-03-06T14:20:00Z',
    },
  ],
  'conv-2': [
    {
      id: 'msg-201',
      conversationId: 'conv-2',
      sender: 'user',
      content: 'Bonjour M. Ndiaye, je suis Mor Keblink de Prospecta. Nous accompagnons les leaders du transit à Dakar dans la qualification automatique de leurs prospects import-export. Seriez-vous disponible pour un court échange ?',
      channel: 'whatsapp',
      timestamp: '2026-03-05T09:00:00Z',
      status: 'read',
    },
    {
      id: 'msg-202',
      conversationId: 'conv-2',
      sender: 'prospect',
      content: 'Bonjour, pouvez-vous me préciser les tarifs pour une équipe de 5 commerciaux ?',
      channel: 'whatsapp',
      timestamp: '2026-03-05T10:15:00Z',
    },
  ],
  'conv-3': [
    {
      id: 'msg-301',
      conversationId: 'conv-3',
      sender: 'user',
      content: 'Bonjour Mariama, j\'ai vu vos récentes annonces de recrutement commercial pour Dakar Tech Solutions. Prospecta aide justement les équipes sales B2B à générer des opportunités qualifiées chaque semaine.',
      channel: 'email',
      timestamp: '2026-03-04T15:00:00Z',
      status: 'read',
    },
    {
      id: 'msg-302',
      conversationId: 'conv-3',
      sender: 'prospect',
      content: 'Bonjour Mor, nous sommes en train de revoir nos outils de prospection pour Q2. Discutons-en la semaine prochaine.',
      channel: 'email',
      timestamp: '2026-03-06T11:00:00Z',
    },
  ],
};

export const initialOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Abonnement Annuel Plateforme B2B',
    prospectId: 'pros-1',
    prospectName: 'Babacar Ndiaye',
    companyName: 'Teranga Logistique & Transit',
    value: 3600000, // FCFA
    stage: 'negotiation',
    probability: 80,
    lastActivityAt: '2026-03-05T10:15:00Z',
    expectedCloseDate: '2026-03-31',
  },
  {
    id: 'opp-2',
    title: 'Module Prospection Salons & Séminaires',
    prospectId: 'pros-2',
    prospectName: 'Aïssatou Diop',
    companyName: 'Hôtel Terrou-Bi Dakar',
    value: 2400000, // FCFA
    stage: 'meeting',
    probability: 60,
    lastActivityAt: '2026-03-06T14:20:00Z',
    expectedCloseDate: '2026-04-15',
  },
  {
    id: 'opp-3',
    title: 'Intégration WhatsApp & Campagnes Agro',
    prospectId: 'pros-3',
    prospectName: 'Cheikh Fall',
    companyName: 'SenAgro Industries',
    value: 1800000, // FCFA
    stage: 'contacted',
    probability: 30,
    lastActivityAt: '2026-03-04T16:45:00Z',
    expectedCloseDate: '2026-04-30',
  },
  {
    id: 'opp-4',
    title: 'Déploiement Équipe Commerciale Tech',
    prospectId: 'pros-5',
    prospectName: 'Mariama Ba',
    companyName: 'Dakar Tech Solutions',
    value: 4200000, // FCFA
    stage: 'qualified',
    probability: 50,
    lastActivityAt: '2026-03-06T11:00:00Z',
    expectedCloseDate: '2026-04-20',
  },
  {
    id: 'opp-5',
    title: 'Distribution Saly & Petite Côte',
    prospectId: 'pros-4',
    prospectName: 'Ousmane Sow',
    companyName: 'Baobab Distribution',
    value: 1200000, // FCFA
    stage: 'new',
    probability: 20,
    lastActivityAt: '2026-03-01T08:30:00Z',
    expectedCloseDate: '2026-05-15',
  },
  {
    id: 'opp-6',
    title: 'Contrat Entreprise Multi-sites',
    prospectId: 'pros-1',
    prospectName: 'Babacar Ndiaye',
    companyName: 'Teranga Logistique & Transit',
    value: 7500000, // FCFA
    stage: 'proposal',
    probability: 70,
    lastActivityAt: '2026-03-03T16:00:00Z',
    expectedCloseDate: '2026-04-10',
  },
];

export const initialAnalytics: AnalyticsSummary = {
  totalProspects: 1245,
  qualifiedProspects: 386,
  activeCampaigns: 8,
  totalOpportunities: 42,
  totalPipelineValue: 48500000, // FCFA
  conversionRate: 14.8, // %
  replyRate: 28.5, // %
  activityTimeline: [
    { period: 'Lun', sent: 120, replies: 32, meetings: 4 },
    { period: 'Mar', sent: 145, replies: 41, meetings: 6 },
    { period: 'Mer', sent: 160, replies: 48, meetings: 7 },
    { period: 'Jeu', sent: 190, replies: 56, meetings: 9 },
    { period: 'Ven', sent: 130, replies: 35, meetings: 5 },
    { period: 'Sam', sent: 40, replies: 12, meetings: 1 },
    { period: 'Dim', sent: 15, replies: 4, meetings: 0 },
  ],
};
